import 'package:quiz_practice/models/question.dart';

final level1QuestionList = [
  Question(
    index: 0,
    question: 'Level 1 Question 1',
    optionA: 'Question 1 Option 1',
    optionB: 'Question 1 Option 2',
    optionC: 'Question 1 Option 3',
    optionD: 'Question 1 Option 4',
    correctAnswer: 'Question 1 Option 1',
  ),
  Question(
    index: 1,
    question: 'Level 1 Question 2',
    optionA: 'Question 2 Option 1',
    optionB: 'Question 2 Option 2',
    optionC: 'Question 2 Option 3',
    optionD: 'Question 2 Option 4',
    correctAnswer: 'Question 2 Option 1',
  ),
  Question(
    index: 2,
    question: 'Level 1 Question 3',
    optionA: 'Question 3 Option 1',
    optionB: 'Question 3 Option 2',
    optionC: 'Question 3 Option 3',
    optionD: 'Question 3 Option 4',
    correctAnswer: 'Question 3 Option 1',
  ),
  Question(
    index: 3,
    question: 'Level 1 Question 4',
    optionA: 'Question 4 Option 1',
    optionB: 'Question 4 Option 2',
    optionC: 'Question 4 Option 3',
    optionD: 'Question 4 Option 4',
    correctAnswer: 'Question 4 Option 1',
  ),
  Question(
    index: 4,
    question: 'Level 1 Question 5',
    optionA: 'Question 5 Option 1',
    optionB: 'Question 5 Option 2',
    optionC: 'Question 5 Option 3',
    optionD: 'Question 5 Option 4',
    correctAnswer: 'Question 5 Option 1',
  ),
  Question(
    index: 5,
    question: 'Level 1 Question 6',
    optionA: 'Question 6 Option 1',
    optionB: 'Question 6 Option 2',
    optionC: 'Question 6 Option 3',
    optionD: 'Question 6 Option 4',
    correctAnswer: 'Question 6 Option 1',
  ),
  Question(
    index: 6,
    question: 'Level 1 Question 7',
    optionA: 'Question 7 Option 1',
    optionB: 'Question 7 Option 2',
    optionC: 'Question 7 Option 3',
    optionD: 'Question 7 Option 4',
    correctAnswer: 'Question 7 Option 1',
  ),
  Question(
    index: 7,
    question: 'Level 1 Question 8',
    optionA: 'Question 8 Option 1',
    optionB: 'Question 8 Option 2',
    optionC: 'Question 8 Option 3',
    optionD: 'Question 8 Option 4',
    correctAnswer: 'Question 8 Option 1',
  ),
  Question(
    index: 8,
    question: 'Level 1 Question 9',
    optionA: 'Question 9 Option 1',
    optionB: 'Question 9 Option 2',
    optionC: 'Question 9 Option 3',
    optionD: 'Question 9 Option 4',
    correctAnswer: 'Question 9 Option 1',
  ),
  Question(
    index: 9,
    question: 'Level 1 Question 10',
    optionA: 'Question 10 Option 1',
    optionB: 'Question 10 Option 2',
    optionC: 'Question 10 Option 3',
    optionD: 'Question 10 Option 4',
    correctAnswer: 'Question 10 Option 1',
  ),
];

final level2QuestionList = [
  Question(
    index: 0,
    question: 'Level 2 Question 1',
    optionA: 'Question 1 Option 1',
    optionB: 'Question 1 Option 2',
    optionC: 'Question 1 Option 3',
    optionD: 'Question 1 Option 4',
    correctAnswer: 'Question 1 Option 2',
  ),
  Question(
    index: 1,
    question: 'Level 2 Question 2',
    optionA: 'Question 2 Option 1',
    optionB: 'Question 2 Option 2',
    optionC: 'Question 2 Option 3',
    optionD: 'Question 2 Option 4',
    correctAnswer: 'Question 2 Option 2',
  ),
  Question(
    index: 2,
    question: 'Level 2 Question 3',
    optionA: 'Question 3 Option 1',
    optionB: 'Question 3 Option 2',
    optionC: 'Question 3 Option 3',
    optionD: 'Question 3 Option 4',
    correctAnswer: 'Question 3 Option 2',
  ),
  Question(
    index: 3,
    question: 'Level 2 Question 4',
    optionA: 'Question 4 Option 1',
    optionB: 'Question 4 Option 2',
    optionC: 'Question 4 Option 3',
    optionD: 'Question 4 Option 4',
    correctAnswer: 'Question 4 Option 2',
  ),
  Question(
    index: 4,
    question: 'Level 2 Question 5',
    optionA: 'Question 5 Option 1',
    optionB: 'Question 5 Option 2',
    optionC: 'Question 5 Option 3',
    optionD: 'Question 5 Option 4',
    correctAnswer: 'Question 5 Option 2',
  ),
  Question(
    index: 5,
    question: 'Level 2 Question 6',
    optionA: 'Question 6 Option 1',
    optionB: 'Question 6 Option 2',
    optionC: 'Question 6 Option 3',
    optionD: 'Question 6 Option 4',
    correctAnswer: 'Question 6 Option 2',
  ),
  Question(
    index: 6,
    question: 'Level 2 Question 7',
    optionA: 'Question 7 Option 1',
    optionB: 'Question 7 Option 2',
    optionC: 'Question 7 Option 3',
    optionD: 'Question 7 Option 4',
    correctAnswer: 'Question 7 Option 2',
  ),
  Question(
    index: 7,
    question: 'Level 2 Question 8',
    optionA: 'Question 8 Option 1',
    optionB: 'Question 8 Option 2',
    optionC: 'Question 8 Option 3',
    optionD: 'Question 8 Option 4',
    correctAnswer: 'Question 8 Option 2',
  ),
  Question(
    index: 8,
    question: 'Level 2 Question 9',
    optionA: 'Question 9 Option 1',
    optionB: 'Question 9 Option 2',
    optionC: 'Question 9 Option 3',
    optionD: 'Question 9 Option 4',
    correctAnswer: 'Question 9 Option 2',
  ),
  Question(
    index: 9,
    question: 'Level 2 Question 10',
    optionA: 'Question 10 Option 1',
    optionB: 'Question 10 Option 2',
    optionC: 'Question 10 Option 3',
    optionD: 'Question 10 Option 4',
    correctAnswer: 'Question 10 Option 2',
  ),
];
